version: '3.3'
services:
  db:
    # build:
    #   context: mysql  
    image: mysql:5.7.22
    ports:
         - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: test
        MYSQL_PASSWORD: test
        MYSQL_DATABASE: test
    volumes:
      - db_local_data:/var/lib/mysql
volumes:
  db_local_data:
    driver: local